version: '3'

services:
  hive:
    image: rubensminoru/hive
    command: /opt/hive/bin/hive --service hiveserver2
    volumes:
    - ./config/core-site.xml:/opt/hive/conf/core-site.xml
    ports:
    - 10000:10000
    - 10002:10002
    depends_on:
      metastore:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-w", "1", "localhost", "10002"]
      interval: 10s
      timeout: 5s
      retries: 3
  metastore:
    image: rubensminoru/hive
    command: /opt/hive/bin/hive --service metastore
    volumes:
    - ./config/core-site.xml:/opt/hive/conf/core-site.xml
    ports:
    - 9083:9083
    - 5556:5556
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-w", "1", "localhost", "9083"]
      interval: 10s
      timeout: 5s
      retries: 3
  postgresql:
    image: postgres:9.5
    volumes:
    - "./tmp/postgres:/var/lib/postgresql/data"
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=hive
    - POSTGRES_USER=hive
    - POSTGRES_DB=metastore
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "metastore" ]
      interval: 10s
      timeout: 5s
      retries: 3
  localstack:
    image: localstack/localstack:0.14
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4567:4567"
    volumes:
      - "./tmp/localstack:/tmp/localstack/data"
      - '/var/run/docker.sock:/var/run/docker.sock'
  coordinator:
    image: rubensminoru/presto
    ports:
      - "8081:8080"
    volumes:
      - "./config/coordinator.properties:/etc/presto/config.properties"
      - "./config/catalog:/etc/presto/catalog"
      - "./config/jvm.config:/opt/presto/etc/jvm.config"
      - "./tmp/coordinator/data:/data"
      - "./tmp/coordinator/worker:/presto"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/v1/info" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      metastore:
        condition: service_healthy
  workers:
    image: rubensminoru/presto
    volumes:
      - "./config/worker.properties:/etc/presto/config.properties"
      - "./config/catalog:/etc/presto/catalog"
      - "./config/jvm.config:/opt/presto/etc/jvm.config"
      - "./tmp/workers/data:/data"
      - "./tmp/workers/worker:/presto"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/v1/info" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      coordinator:
        condition: service_healthy
  hue:
    image: gethue/hue:latest
    ports:
      - "8888:8888"
    depends_on:
      coordinator:
        condition: service_healthy
      hive:
        condition: service_healthy
    volumes:
      - "./config/hue/z-hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini"
      - "./config/hue/log.conf:/etc/hue/conf/log.conf"
